// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycnrewqwwlmhbxonlmxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljbnJld3F3d2xtaGJ4b25sbXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTQyMzEsImV4cCI6MjA2ODU5MDIzMX0.9OgdYWl3V1-tlaLl-PHNwIrU2wMBasVodBy1qRwFaOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});